-- Run this in Supabase SQL editor to create the registrations table.

create table if not exists marathon.registrations (
  id bigint generated by default as identity primary key,
  phone text not null,
  full_name text not null,
  email text not null,
  date_of_birth date not null,
  category text not null,
  gender text not null,
  country text not null,
  city text not null,
  state text,
  wants_tshirt boolean not null default false,
  t_shirt_size text,
  payment_status text not null default 'PENDING' check (payment_status in ('PENDING', 'DONE', 'FAILED')),
  identification_number text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists idx_registrations_identification_number
  on marathon.registrations (identification_number);

-- RLS: allow anonymous insert (registration form) and update/select for payment flow
alter table marathon.registrations enable row level security;

create policy "Allow anonymous insert"
  on marathon.registrations
  for insert
  with check (true);

create policy "Allow anonymous update"
  on marathon.registrations
  for update
  using (true)
  with check (true);

create policy "Allow anonymous select"
  on marathon.registrations
  for select
  using (true);
